package xxkq.oracle.apps.xbol.v2.employee.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxkq.oracle.apps.xbol.v2.employee.schema.server.TransactionLineIssueEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionReturnLineVORowImpl
  extends OAViewRowImpl
{
  public static final int TRANSACTIONID = 0;
  public static final int TRANSACTIONHEADERID = 1;
  public static final int REQUISITIONLINEID = 2;
  public static final int TRANSACTIONLINENUMBER = 3;
  public static final int UNIFORMSETLINEID = 4;
  public static final int TRANSACTIONDATE = 5;
  public static final int TRANSACTIONQTY = 6;
  public static final int INVENTORYITEMID = 7;
  public static final int CATEGORYID = 8;
  public static final int LOCATORID = 9;
  public static final int SUBINVENTORY = 10;
  public static final int ORGANIZATIONID = 11;
  public static final int CHARGEDQTY = 12;
  public static final int UNITPRICE = 13;
  public static final int AMOUNTCHARGED = 14;
  public static final int TRANSACTIONREASONCODE = 15;
  public static final int LINESTATUS = 16;
  public static final int REMARKS = 17;
  public static final int PARENTTRANSACTIONID = 18;
  public static final int CREATEDBY = 19;
  public static final int CREATIONDATE = 20;
  public static final int LASTUPDATEDBY = 21;
  public static final int LASTUPDATEDATE = 22;
  public static final int LASTUPDATELOGIN = 23;
  public static final int ATTRIBUTE1 = 24;
  public static final int ATTRIBUTE2 = 25;
  public static final int ATTRIBUTE3 = 26;
  public static final int ATTRIBUTE4 = 27;
  public static final int ATTRIBUTE5 = 28;
  public static final int ATTRIBUTE6 = 29;
  public static final int ATTRIBUTE7 = 30;
  public static final int ATTRIBUTE8 = 31;
  public static final int ATTRIBUTE9 = 32;
  public static final int ATTRIBUTE10 = 33;
  public static final int ATTRIBUTE11 = 34;
  public static final int ATTRIBUTE12 = 35;
  public static final int ATTRIBUTE13 = 36;
  public static final int ATTRIBUTE14 = 37;
  public static final int ATTRIBUTE15 = 38;
  public static final int ATTRIBUTE16 = 39;
  public static final int ATTRIBUTE17 = 40;
  public static final int ATTRIBUTE18 = 41;
  public static final int ATTRIBUTE19 = 42;
  public static final int ATTRIBUTE20 = 43;
  public static final int ITEMCODE = 44;
  public static final int DESCRIPTION = 45;
  public static final int PRIMARYUNITOFMEASURE = 46;
  public static final int REQUESTEDQTY = 47;
  public static final int TOTALQTYRETURNED = 48;
  public static final int TOTALISSUEDQTY = 49;
  public static final int QUANTITYPENDING = 50;
  public static final int ITEMCATEGORY = 51;
  public static final int ONHANDQUANTITY = 52;
  public static final int ORGANIZATIONIDTRANSIENT = 53;
  public static final int LOCATORIDTRANSIENT = 54;
  public static final int CHARGABLEQTY = 55;
  public static final int RETURNEDQTY = 56;
  public static final int RECEIPTVALUE = 57;

  /**This is the default constructor (do not remove)
   */
  public TransactionReturnLineVORowImpl()
  {
  }

  /**Gets TransactionLineIssueEO entity object.
   */
  public TransactionLineIssueEOImpl getTransactionLineIssueEO()
  {
    return (TransactionLineIssueEOImpl) getEntity(0);
  }

  /**Gets the attribute value for TRANSACTION_ID using the alias name TransactionId
   */
  public Number getTransactionId()
  {
    return (Number) getAttributeInternal(TRANSACTIONID);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId
   */
  public void setTransactionId(Number value)
  {
    setAttributeInternal(TRANSACTIONID, value);
  }

  /**Gets the attribute value for TRANSACTION_HEADER_ID using the alias name TransactionHeaderId
   */
  public Number getTransactionHeaderId()
  {
    return (Number) getAttributeInternal(TRANSACTIONHEADERID);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_HEADER_ID using the alias name TransactionHeaderId
   */
  public void setTransactionHeaderId(Number value)
  {
    setAttributeInternal(TRANSACTIONHEADERID, value);
  }

  /**Gets the attribute value for REQUISITION_LINE_ID using the alias name RequisitionLineId
   */
  public Number getRequisitionLineId()
  {
    return (Number) getAttributeInternal(REQUISITIONLINEID);
  }

  /**Sets <code>value</code> as attribute value for REQUISITION_LINE_ID using the alias name RequisitionLineId
   */
  public void setRequisitionLineId(Number value)
  {
    setAttributeInternal(REQUISITIONLINEID, value);
  }

  /**Gets the attribute value for TRANSACTION_LINE_NUMBER using the alias name TransactionLineNumber
   */
  public Number getTransactionLineNumber()
  {
    return (Number) getAttributeInternal(TRANSACTIONLINENUMBER);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_LINE_NUMBER using the alias name TransactionLineNumber
   */
  public void setTransactionLineNumber(Number value)
  {
    setAttributeInternal(TRANSACTIONLINENUMBER, value);
  }

  /**Gets the attribute value for UNIFORM_SET_LINE_ID using the alias name UniformSetLineId
   */
  public Number getUniformSetLineId()
  {
    return (Number) getAttributeInternal(UNIFORMSETLINEID);
  }

  /**Sets <code>value</code> as attribute value for UNIFORM_SET_LINE_ID using the alias name UniformSetLineId
   */
  public void setUniformSetLineId(Number value)
  {
    setAttributeInternal(UNIFORMSETLINEID, value);
  }

  /**Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate
   */
  public Date getTransactionDate()
  {
    return (Date) getAttributeInternal(TRANSACTIONDATE);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate
   */
  public void setTransactionDate(Date value)
  {
    setAttributeInternal(TRANSACTIONDATE, value);
  }

  /**Gets the attribute value for TRANSACTION_QTY using the alias name TransactionQty
   */
  public Number getTransactionQty()
  {
    return (Number) getAttributeInternal(TRANSACTIONQTY);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_QTY using the alias name TransactionQty
   */
  public void setTransactionQty(Number value)
  {
    setAttributeInternal(TRANSACTIONQTY, value);
  }

  /**Gets the attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId
   */
  public Number getInventoryItemId()
  {
    return (Number) getAttributeInternal(INVENTORYITEMID);
  }

  /**Sets <code>value</code> as attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId
   */
  public void setInventoryItemId(Number value)
  {
    setAttributeInternal(INVENTORYITEMID, value);
  }

  /**Gets the attribute value for CATEGORY_ID using the alias name CategoryId
   */
  public Number getCategoryId()
  {
    return (Number) getAttributeInternal(CATEGORYID);
  }

  /**Sets <code>value</code> as attribute value for CATEGORY_ID using the alias name CategoryId
   */
  public void setCategoryId(Number value)
  {
    setAttributeInternal(CATEGORYID, value);
  }

  /**Gets the attribute value for LOCATOR_ID using the alias name LocatorId
   */
  public Number getLocatorId()
  {
    return (Number) getAttributeInternal(LOCATORID);
  }

  /**Sets <code>value</code> as attribute value for LOCATOR_ID using the alias name LocatorId
   */
  public void setLocatorId(Number value)
  {
    setAttributeInternal(LOCATORID, value);
  }

  /**Gets the attribute value for SUBINVENTORY using the alias name Subinventory
   */
  public String getSubinventory()
  {
    return (String) getAttributeInternal(SUBINVENTORY);
  }

  /**Sets <code>value</code> as attribute value for SUBINVENTORY using the alias name Subinventory
   */
  public void setSubinventory(String value)
  {
    setAttributeInternal(SUBINVENTORY, value);
  }

  /**Gets the attribute value for ORGANIZATION_ID using the alias name OrganizationId
   */
  public Number getOrganizationId()
  {
    return (Number) getAttributeInternal(ORGANIZATIONID);
  }

  /**Sets <code>value</code> as attribute value for ORGANIZATION_ID using the alias name OrganizationId
   */
  public void setOrganizationId(Number value)
  {
    setAttributeInternal(ORGANIZATIONID, value);
  }

  /**Gets the attribute value for the calculated attribute ChargedQty
   */
  public Number getChargedQty()
  {
    return (Number) getAttributeInternal(CHARGEDQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ChargedQty
   */
  public void setChargedQty(Number value)
  {
    setAttributeInternal(CHARGEDQTY, value);
  }

  /**Gets the attribute value for UNIT_PRICE using the alias name UnitPrice
   */
  public Number getUnitPrice()
  {
    return (Number) getAttributeInternal(UNITPRICE);
  }

  /**Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice
   */
  public void setUnitPrice(Number value)
  {
    setAttributeInternal(UNITPRICE, value);
  }

  /**Gets the attribute value for the calculated attribute AmountCharged
   */
  public Number getAmountCharged()
  {
    return (Number) getAttributeInternal(AMOUNTCHARGED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute AmountCharged
   */
  public void setAmountCharged(Number value)
  {
    setAttributeInternal(AMOUNTCHARGED, value);
  }

  /**Gets the attribute value for the calculated attribute TransactionReasonCode
   */
  public String getTransactionReasonCode()
  {
    return (String) getAttributeInternal(TRANSACTIONREASONCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TransactionReasonCode
   */
  public void setTransactionReasonCode(String value)
  {
    setAttributeInternal(TRANSACTIONREASONCODE, value);
  }

  /**Gets the attribute value for the calculated attribute LineStatus
   */
  public String getLineStatus()
  {
    return (String) getAttributeInternal(LINESTATUS);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LineStatus
   */
  public void setLineStatus(String value)
  {
    setAttributeInternal(LINESTATUS, value);
  }

  /**Gets the attribute value for REMARKS using the alias name Remarks
   */
  public String getRemarks()
  {
    return (String) getAttributeInternal(REMARKS);
  }

  /**Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks
   */
  public void setRemarks(String value)
  {
    setAttributeInternal(REMARKS, value);
  }

  /**Gets the attribute value for the calculated attribute ParentTransactionId
   */
  public Number getParentTransactionId()
  {
    return (Number) getAttributeInternal(PARENTTRANSACTIONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ParentTransactionId
   */
  public void setParentTransactionId(Number value)
  {
    setAttributeInternal(PARENTTRANSACTIONID, value);
  }

  /**Gets the attribute value for the calculated attribute CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for the calculated attribute LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number) getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for the calculated attribute LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for the calculated attribute LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number) getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute1
   */
  public String getAttribute1()
  {
    return (String) getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute2
   */
  public String getAttribute2()
  {
    return (String) getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute3
   */
  public String getAttribute3()
  {
    return (String) getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute4
   */
  public String getAttribute4()
  {
    return (String) getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute5
   */
  public String getAttribute5()
  {
    return (String) getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute6
   */
  public String getAttribute6()
  {
    return (String) getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute7
   */
  public String getAttribute7()
  {
    return (String) getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute8
   */
  public String getAttribute8()
  {
    return (String) getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute9
   */
  public String getAttribute9()
  {
    return (String) getAttributeInternal(ATTRIBUTE9);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
   */
  public void setAttribute9(String value)
  {
    setAttributeInternal(ATTRIBUTE9, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute10
   */
  public String getAttribute10()
  {
    return (String) getAttributeInternal(ATTRIBUTE10);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute10
   */
  public void setAttribute10(String value)
  {
    setAttributeInternal(ATTRIBUTE10, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute11
   */
  public String getAttribute11()
  {
    return (String) getAttributeInternal(ATTRIBUTE11);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute11
   */
  public void setAttribute11(String value)
  {
    setAttributeInternal(ATTRIBUTE11, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute12
   */
  public String getAttribute12()
  {
    return (String) getAttributeInternal(ATTRIBUTE12);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute12
   */
  public void setAttribute12(String value)
  {
    setAttributeInternal(ATTRIBUTE12, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute13
   */
  public String getAttribute13()
  {
    return (String) getAttributeInternal(ATTRIBUTE13);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute13
   */
  public void setAttribute13(String value)
  {
    setAttributeInternal(ATTRIBUTE13, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute14
   */
  public String getAttribute14()
  {
    return (String) getAttributeInternal(ATTRIBUTE14);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute14
   */
  public void setAttribute14(String value)
  {
    setAttributeInternal(ATTRIBUTE14, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute15
   */
  public String getAttribute15()
  {
    return (String) getAttributeInternal(ATTRIBUTE15);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute15
   */
  public void setAttribute15(String value)
  {
    setAttributeInternal(ATTRIBUTE15, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute16
   */
  public String getAttribute16()
  {
    return (String) getAttributeInternal(ATTRIBUTE16);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute16
   */
  public void setAttribute16(String value)
  {
    setAttributeInternal(ATTRIBUTE16, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute17
   */
  public String getAttribute17()
  {
    return (String) getAttributeInternal(ATTRIBUTE17);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute17
   */
  public void setAttribute17(String value)
  {
    setAttributeInternal(ATTRIBUTE17, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute18
   */
  public String getAttribute18()
  {
    return (String) getAttributeInternal(ATTRIBUTE18);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute18
   */
  public void setAttribute18(String value)
  {
    setAttributeInternal(ATTRIBUTE18, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute19
   */
  public String getAttribute19()
  {
    return (String) getAttributeInternal(ATTRIBUTE19);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute19
   */
  public void setAttribute19(String value)
  {
    setAttributeInternal(ATTRIBUTE19, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute20
   */
  public String getAttribute20()
  {
    return (String) getAttributeInternal(ATTRIBUTE20);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute20
   */
  public void setAttribute20(String value)
  {
    setAttributeInternal(ATTRIBUTE20, value);
  }

  /**Gets the attribute value for the calculated attribute ItemCode
   */
  public String getItemCode()
  {
    return (String) getAttributeInternal(ITEMCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ItemCode
   */
  public void setItemCode(String value)
  {
    setAttributeInternal(ITEMCODE, value);
  }

  /**Gets the attribute value for the calculated attribute Description
   */
  public String getDescription()
  {
    return (String) getAttributeInternal(DESCRIPTION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryUnitOfMeasure
   */
  public String getPrimaryUnitOfMeasure()
  {
    return (String) getAttributeInternal(PRIMARYUNITOFMEASURE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryUnitOfMeasure
   */
  public void setPrimaryUnitOfMeasure(String value)
  {
    setAttributeInternal(PRIMARYUNITOFMEASURE, value);
  }

  /**Gets the attribute value for the calculated attribute RequestedQty
   */
  public Number getRequestedQty()
  {
    return (Number) getAttributeInternal(REQUESTEDQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RequestedQty
   */
  public void setRequestedQty(Number value)
  {
    setAttributeInternal(REQUESTEDQTY, value);
  }

  /**Gets the attribute value for the calculated attribute TotalQtyReturned
   */
  public Number getTotalQtyReturned()
  {
    return (Number) getAttributeInternal(TOTALQTYRETURNED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TotalQtyReturned
   */
  public void setTotalQtyReturned(Number value)
  {
    setAttributeInternal(TOTALQTYRETURNED, value);
  }

  /**Gets the attribute value for the calculated attribute Totalissuedqty
   */
  public Number getTotalissuedqty()
  {
    return (Number) getAttributeInternal(TOTALISSUEDQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Totalissuedqty
   */
  public void setTotalissuedqty(Number value)
  {
    setAttributeInternal(TOTALISSUEDQTY, value);
  }

  /**Gets the attribute value for the calculated attribute Quantitypending
   */
  public Number getQuantitypending()
  {
    return (Number) getAttributeInternal(QUANTITYPENDING);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Quantitypending
   */
  public void setQuantitypending(Number value)
  {
    setAttributeInternal(QUANTITYPENDING, value);
  }

  /**Gets the attribute value for the calculated attribute ItemCategory
   */
  public String getItemCategory()
  {
    return (String) getAttributeInternal(ITEMCATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ItemCategory
   */
  public void setItemCategory(String value)
  {
    setAttributeInternal(ITEMCATEGORY, value);
  }

  /**Gets the attribute value for the calculated attribute OnhandQuantity
   */
  public Number getOnhandQuantity()
  {
    return (Number) getAttributeInternal(ONHANDQUANTITY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OnhandQuantity
   */
  public void setOnhandQuantity(Number value)
  {
    setAttributeInternal(ONHANDQUANTITY, value);
  }

  /**Gets the attribute value for the calculated attribute ChargableQty
   */
  public Number getChargableQty()
  {
    return (Number) getAttributeInternal(CHARGABLEQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ChargableQty
   */
  public void setChargableQty(Number value)
  {
    setAttributeInternal(CHARGABLEQTY, value);
  }

  /**Gets the attribute value for the calculated attribute ReturnedQty
   */
  public Number getReturnedQty()
  {
    return (Number) getAttributeInternal(RETURNEDQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ReturnedQty
   */
  public void setReturnedQty(Number value)
  {
    setAttributeInternal(RETURNEDQTY, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    switch (index)
    {
      case TRANSACTIONID:
        return getTransactionId();
      case TRANSACTIONHEADERID:
        return getTransactionHeaderId();
      case REQUISITIONLINEID:
        return getRequisitionLineId();
      case TRANSACTIONLINENUMBER:
        return getTransactionLineNumber();
      case UNIFORMSETLINEID:
        return getUniformSetLineId();
      case TRANSACTIONDATE:
        return getTransactionDate();
      case TRANSACTIONQTY:
        return getTransactionQty();
      case INVENTORYITEMID:
        return getInventoryItemId();
      case CATEGORYID:
        return getCategoryId();
      case LOCATORID:
        return getLocatorId();
      case SUBINVENTORY:
        return getSubinventory();
      case ORGANIZATIONID:
        return getOrganizationId();
      case CHARGEDQTY:
        return getChargedQty();
      case UNITPRICE:
        return getUnitPrice();
      case AMOUNTCHARGED:
        return getAmountCharged();
      case TRANSACTIONREASONCODE:
        return getTransactionReasonCode();
      case LINESTATUS:
        return getLineStatus();
      case REMARKS:
        return getRemarks();
      case PARENTTRANSACTIONID:
        return getParentTransactionId();
      case CREATEDBY:
        return getCreatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case ATTRIBUTE1:
        return getAttribute1();
      case ATTRIBUTE2:
        return getAttribute2();
      case ATTRIBUTE3:
        return getAttribute3();
      case ATTRIBUTE4:
        return getAttribute4();
      case ATTRIBUTE5:
        return getAttribute5();
      case ATTRIBUTE6:
        return getAttribute6();
      case ATTRIBUTE7:
        return getAttribute7();
      case ATTRIBUTE8:
        return getAttribute8();
      case ATTRIBUTE9:
        return getAttribute9();
      case ATTRIBUTE10:
        return getAttribute10();
      case ATTRIBUTE11:
        return getAttribute11();
      case ATTRIBUTE12:
        return getAttribute12();
      case ATTRIBUTE13:
        return getAttribute13();
      case ATTRIBUTE14:
        return getAttribute14();
      case ATTRIBUTE15:
        return getAttribute15();
      case ATTRIBUTE16:
        return getAttribute16();
      case ATTRIBUTE17:
        return getAttribute17();
      case ATTRIBUTE18:
        return getAttribute18();
      case ATTRIBUTE19:
        return getAttribute19();
      case ATTRIBUTE20:
        return getAttribute20();
      case ITEMCODE:
        return getItemCode();
      case DESCRIPTION:
        return getDescription();
      case PRIMARYUNITOFMEASURE:
        return getPrimaryUnitOfMeasure();
      case REQUESTEDQTY:
        return getRequestedQty();
      case TOTALQTYRETURNED:
        return getTotalQtyReturned();
      case TOTALISSUEDQTY:
        return getTotalissuedqty();
      case QUANTITYPENDING:
        return getQuantitypending();
      case ITEMCATEGORY:
        return getItemCategory();
      case ONHANDQUANTITY:
        return getOnhandQuantity();
      case ORGANIZATIONIDTRANSIENT:
        return getOrganizationIDTransient();
      case LOCATORIDTRANSIENT:
        return getLocatorIDTransient();
      case CHARGABLEQTY:
        return getChargableQty();
      case RETURNEDQTY:
        return getReturnedQty();
      case RECEIPTVALUE:
        return getReceiptvalue();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    switch (index)
    {
      case TRANSACTIONID:
        setTransactionId((Number)value);
        return;
      case TRANSACTIONHEADERID:
        setTransactionHeaderId((Number)value);
        return;
      case REQUISITIONLINEID:
        setRequisitionLineId((Number)value);
        return;
      case TRANSACTIONLINENUMBER:
        setTransactionLineNumber((Number)value);
        return;
      case UNIFORMSETLINEID:
        setUniformSetLineId((Number)value);
        return;
      case TRANSACTIONDATE:
        setTransactionDate((Date)value);
        return;
      case TRANSACTIONQTY:
        setTransactionQty((Number)value);
        return;
      case INVENTORYITEMID:
        setInventoryItemId((Number)value);
        return;
      case CATEGORYID:
        setCategoryId((Number)value);
        return;
      case LOCATORID:
        setLocatorId((Number)value);
        return;
      case SUBINVENTORY:
        setSubinventory((String)value);
        return;
      case ORGANIZATIONID:
        setOrganizationId((Number)value);
        return;
      case CHARGEDQTY:
        setChargedQty((Number)value);
        return;
      case UNITPRICE:
        setUnitPrice((Number)value);
        return;
      case AMOUNTCHARGED:
        setAmountCharged((Number)value);
        return;
      case TRANSACTIONREASONCODE:
        setTransactionReasonCode((String)value);
        return;
      case LINESTATUS:
        setLineStatus((String)value);
        return;
      case REMARKS:
        setRemarks((String)value);
        return;
      case PARENTTRANSACTIONID:
        setParentTransactionId((Number)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case ATTRIBUTE2:
        setAttribute2((String)value);
        return;
      case ATTRIBUTE3:
        setAttribute3((String)value);
        return;
      case ATTRIBUTE4:
        setAttribute4((String)value);
        return;
      case ATTRIBUTE5:
        setAttribute5((String)value);
        return;
      case ATTRIBUTE6:
        setAttribute6((String)value);
        return;
      case ATTRIBUTE7:
        setAttribute7((String)value);
        return;
      case ATTRIBUTE8:
        setAttribute8((String)value);
        return;
      case ATTRIBUTE9:
        setAttribute9((String)value);
        return;
      case ATTRIBUTE10:
        setAttribute10((String)value);
        return;
      case ATTRIBUTE11:
        setAttribute11((String)value);
        return;
      case ATTRIBUTE12:
        setAttribute12((String)value);
        return;
      case ATTRIBUTE13:
        setAttribute13((String)value);
        return;
      case ATTRIBUTE14:
        setAttribute14((String)value);
        return;
      case ATTRIBUTE15:
        setAttribute15((String)value);
        return;
      case ATTRIBUTE16:
        setAttribute16((String)value);
        return;
      case ATTRIBUTE17:
        setAttribute17((String)value);
        return;
      case ATTRIBUTE18:
        setAttribute18((String)value);
        return;
      case ATTRIBUTE19:
        setAttribute19((String)value);
        return;
      case ATTRIBUTE20:
        setAttribute20((String)value);
        return;
      case ITEMCODE:
        setItemCode((String)value);
        return;
      case DESCRIPTION:
        setDescription((String)value);
        return;
      case PRIMARYUNITOFMEASURE:
        setPrimaryUnitOfMeasure((String)value);
        return;
      case REQUESTEDQTY:
        setRequestedQty((Number)value);
        return;
      case TOTALQTYRETURNED:
        setTotalQtyReturned((Number)value);
        return;
      case TOTALISSUEDQTY:
        setTotalissuedqty((Number)value);
        return;
      case QUANTITYPENDING:
        setQuantitypending((Number)value);
        return;
      case ITEMCATEGORY:
        setItemCategory((String)value);
        return;
      case ONHANDQUANTITY:
        setOnhandQuantity((Number)value);
        return;
      case ORGANIZATIONIDTRANSIENT:
        setOrganizationIDTransient((String)value);
        return;
      case LOCATORIDTRANSIENT:
        setLocatorIDTransient((String)value);
        return;
      case CHARGABLEQTY:
        setChargableQty((Number)value);
        return;
      case RETURNEDQTY:
        setReturnedQty((Number)value);
        return;
      case RECEIPTVALUE:
        setReceiptvalue((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Gets the attribute value for the calculated attribute OrganizationIDTransient
   */
  public String getOrganizationIDTransient()
  {
    return (String) getAttributeInternal(ORGANIZATIONIDTRANSIENT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationIDTransient
   */
  public void setOrganizationIDTransient(String value)
  {
    setAttributeInternal(ORGANIZATIONIDTRANSIENT, value);
  }


  /**Gets the attribute value for the calculated attribute Receiptvalue
   */
  public Number getReceiptvalue()
  {
    return (Number) getAttributeInternal(RECEIPTVALUE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Receiptvalue
   */
  public void setReceiptvalue(Number value)
  {
    setAttributeInternal(RECEIPTVALUE, value);
  }


  /**Gets the attribute value for the calculated attribute LocatorIDTransient
   */
  public String getLocatorIDTransient()
  {
    return (String) getAttributeInternal(LOCATORIDTRANSIENT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LocatorIDTransient
   */
  public void setLocatorIDTransient(String value)
  {
    setAttributeInternal(LOCATORIDTRANSIENT, value);
  }
}
