package xxkq.oracle.apps.xbol.v2.employee.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxkq.oracle.apps.xbol.v2.employee.schema.server.TransactionHeaderIssueEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionHeaderReturnVORowImpl
  extends OAViewRowImpl
{
  public static final int TRANSACTIONHEADERID = 0;
  public static final int REQUISITIONHEADERID = 1;
  public static final int TRANSACTIONTYPE = 2;
  public static final int RETURNTYPE = 3;
  public static final int TRANSACTIONNUMBER = 4;
  public static final int TRANSACTIONSTATUS = 5;
  public static final int TRANSACTIONDATE = 6;
  public static final int UNIFORMSETID = 7;
  public static final int PERSONID = 8;
  public static final int BUSINESSGROUPID = 9;
  public static final int REMARKS = 10;
  public static final int CREATEDBY = 11;
  public static final int CREATIONDATE = 12;
  public static final int LASTUPDATEDBY = 13;
  public static final int LASTUPDATEDATE = 14;
  public static final int LASTUPDATELOGIN = 15;
  public static final int ATTRIBUTE1 = 16;
  public static final int ATTRIBUTE2 = 17;
  public static final int ATTRIBUTE3 = 18;
  public static final int ATTRIBUTE4 = 19;
  public static final int ATTRIBUTE5 = 20;
  public static final int ATTRIBUTE6 = 21;
  public static final int ATTRIBUTE7 = 22;
  public static final int ATTRIBUTE8 = 23;
  public static final int ATTRIBUTE9 = 24;
  public static final int ATTRIBUTE10 = 25;
  public static final int ATTRIBUTE11 = 26;
  public static final int ATTRIBUTE12 = 27;
  public static final int ATTRIBUTE13 = 28;
  public static final int ATTRIBUTE14 = 29;
  public static final int ATTRIBUTE15 = 30;
  public static final int ATTRIBUTE16 = 31;
  public static final int ATTRIBUTE17 = 32;
  public static final int ATTRIBUTE18 = 33;
  public static final int ATTRIBUTE19 = 34;
  public static final int ATTRIBUTE20 = 35;
  public static final int EMPLOYEENUMBER = 36;
  public static final int EMPLOYEENAME = 37;
  public static final int REQUISITIONSTATUS = 38;
  public static final int UNIFORMSETNAME = 39;
  public static final int PREPARERNAME = 40;
  public static final int REQUISITIONCREATIONDATE = 41;
  public static final int CONTACTNUMBER = 42;
  public static final int REQUISITIONNUMBER = 43;
  public static final int REQUISITIONTYPE = 44;
  public static final int APPROVERNAME = 45;

  /**This is the default constructor (do not remove)
   */
  public TransactionHeaderReturnVORowImpl()
  {
  }

  /**Gets TransactionHeaderIssueEO entity object.
   */
  public TransactionHeaderIssueEOImpl getTransactionHeaderIssueEO()
  {
    return (TransactionHeaderIssueEOImpl) getEntity(0);
  }

  /**Gets the attribute value for TRANSACTION_HEADER_ID using the alias name TransactionHeaderId
   */
  public Number getTransactionHeaderId()
  {
    return (Number) getAttributeInternal(TRANSACTIONHEADERID);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_HEADER_ID using the alias name TransactionHeaderId
   */
  public void setTransactionHeaderId(Number value)
  {
    setAttributeInternal(TRANSACTIONHEADERID, value);
  }

  /**Gets the attribute value for REQUISITION_HEADER_ID using the alias name RequisitionHeaderId
   */
  public Number getRequisitionHeaderId()
  {
    return (Number) getAttributeInternal(REQUISITIONHEADERID);
  }

  /**Sets <code>value</code> as attribute value for REQUISITION_HEADER_ID using the alias name RequisitionHeaderId
   */
  public void setRequisitionHeaderId(Number value)
  {
    setAttributeInternal(REQUISITIONHEADERID, value);
  }

  /**Gets the attribute value for TRANSACTION_TYPE using the alias name TransactionType
   */
  public String getTransactionType()
  {
    return (String) getAttributeInternal(TRANSACTIONTYPE);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_TYPE using the alias name TransactionType
   */
  public void setTransactionType(String value)
  {
    setAttributeInternal(TRANSACTIONTYPE, value);
  }

  /**Gets the attribute value for RETURN_TYPE using the alias name ReturnType
   */
  public String getReturnType()
  {
    return (String) getAttributeInternal(RETURNTYPE);
  }

  /**Sets <code>value</code> as attribute value for RETURN_TYPE using the alias name ReturnType
   */
  public void setReturnType(String value)
  {
    setAttributeInternal(RETURNTYPE, value);
  }

  /**Gets the attribute value for TRANSACTION_NUMBER using the alias name TransactionNumber
   */
  public String getTransactionNumber()
  {
    return (String) getAttributeInternal(TRANSACTIONNUMBER);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_NUMBER using the alias name TransactionNumber
   */
  public void setTransactionNumber(String value)
  {
    setAttributeInternal(TRANSACTIONNUMBER, value);
  }

  /**Gets the attribute value for TRANSACTION_STATUS using the alias name TransactionStatus
   */
  public String getTransactionStatus()
  {
    return (String) getAttributeInternal(TRANSACTIONSTATUS);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_STATUS using the alias name TransactionStatus
   */
  public void setTransactionStatus(String value)
  {
    setAttributeInternal(TRANSACTIONSTATUS, value);
  }

  /**Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate
   */
  public Date getTransactionDate()
  {
    return (Date) getAttributeInternal(TRANSACTIONDATE);
  }

  /**Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate
   */
  public void setTransactionDate(Date value)
  {
    setAttributeInternal(TRANSACTIONDATE, value);
  }

  /**Gets the attribute value for UNIFORM_SET_ID using the alias name UniformSetId
   */
  public Number getUniformSetId()
  {
    return (Number) getAttributeInternal(UNIFORMSETID);
  }

  /**Sets <code>value</code> as attribute value for UNIFORM_SET_ID using the alias name UniformSetId
   */
  public void setUniformSetId(Number value)
  {
    setAttributeInternal(UNIFORMSETID, value);
  }

  /**Gets the attribute value for PERSON_ID using the alias name PersonId
   */
  public Number getPersonId()
  {
    return (Number) getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId
   */
  public void setPersonId(Number value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for BUSINESS_GROUP_ID using the alias name BusinessGroupId
   */
  public Number getBusinessGroupId()
  {
    return (Number) getAttributeInternal(BUSINESSGROUPID);
  }

  /**Sets <code>value</code> as attribute value for BUSINESS_GROUP_ID using the alias name BusinessGroupId
   */
  public void setBusinessGroupId(Number value)
  {
    setAttributeInternal(BUSINESSGROUPID, value);
  }

  /**Gets the attribute value for REMARKS using the alias name Remarks
   */
  public String getRemarks()
  {
    return (String) getAttributeInternal(REMARKS);
  }

  /**Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks
   */
  public void setRemarks(String value)
  {
    setAttributeInternal(REMARKS, value);
  }

  /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number) getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number) getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String) getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String) getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String) getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String) getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String) getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String) getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String) getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String) getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
   */
  public String getAttribute9()
  {
    return (String) getAttributeInternal(ATTRIBUTE9);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
   */
  public void setAttribute9(String value)
  {
    setAttributeInternal(ATTRIBUTE9, value);
  }

  /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
   */
  public String getAttribute10()
  {
    return (String) getAttributeInternal(ATTRIBUTE10);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
   */
  public void setAttribute10(String value)
  {
    setAttributeInternal(ATTRIBUTE10, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute11
   */
  public String getAttribute11()
  {
    return (String) getAttributeInternal(ATTRIBUTE11);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute11
   */
  public void setAttribute11(String value)
  {
    setAttributeInternal(ATTRIBUTE11, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute12
   */
  public String getAttribute12()
  {
    return (String) getAttributeInternal(ATTRIBUTE12);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute12
   */
  public void setAttribute12(String value)
  {
    setAttributeInternal(ATTRIBUTE12, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute13
   */
  public String getAttribute13()
  {
    return (String) getAttributeInternal(ATTRIBUTE13);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute13
   */
  public void setAttribute13(String value)
  {
    setAttributeInternal(ATTRIBUTE13, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute14
   */
  public String getAttribute14()
  {
    return (String) getAttributeInternal(ATTRIBUTE14);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute14
   */
  public void setAttribute14(String value)
  {
    setAttributeInternal(ATTRIBUTE14, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute15
   */
  public String getAttribute15()
  {
    return (String) getAttributeInternal(ATTRIBUTE15);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute15
   */
  public void setAttribute15(String value)
  {
    setAttributeInternal(ATTRIBUTE15, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute16
   */
  public String getAttribute16()
  {
    return (String) getAttributeInternal(ATTRIBUTE16);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute16
   */
  public void setAttribute16(String value)
  {
    setAttributeInternal(ATTRIBUTE16, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute17
   */
  public String getAttribute17()
  {
    return (String) getAttributeInternal(ATTRIBUTE17);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute17
   */
  public void setAttribute17(String value)
  {
    setAttributeInternal(ATTRIBUTE17, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute18
   */
  public String getAttribute18()
  {
    return (String) getAttributeInternal(ATTRIBUTE18);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute18
   */
  public void setAttribute18(String value)
  {
    setAttributeInternal(ATTRIBUTE18, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute19
   */
  public String getAttribute19()
  {
    return (String) getAttributeInternal(ATTRIBUTE19);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute19
   */
  public void setAttribute19(String value)
  {
    setAttributeInternal(ATTRIBUTE19, value);
  }

  /**Gets the attribute value for the calculated attribute Attribute20
   */
  public String getAttribute20()
  {
    return (String) getAttributeInternal(ATTRIBUTE20);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute20
   */
  public void setAttribute20(String value)
  {
    setAttributeInternal(ATTRIBUTE20, value);
  }

  /**Gets the attribute value for the calculated attribute Employeenumber
   */
  public String getEmployeenumber()
  {
    return (String) getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Employeenumber
   */
  public void setEmployeenumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute EmployeeName
   */
  public String getEmployeeName()
  {
    return (String) getAttributeInternal(EMPLOYEENAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeName
   */
  public void setEmployeeName(String value)
  {
    setAttributeInternal(EMPLOYEENAME, value);
  }

  /**Gets the attribute value for the calculated attribute RequisitionStatus
   */
  public String getRequisitionStatus()
  {
    return (String) getAttributeInternal(REQUISITIONSTATUS);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RequisitionStatus
   */
  public void setRequisitionStatus(String value)
  {
    setAttributeInternal(REQUISITIONSTATUS, value);
  }

  /**Gets the attribute value for the calculated attribute UniformSetName
   */
  public String getUniformSetName()
  {
    return (String) getAttributeInternal(UNIFORMSETNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UniformSetName
   */
  public void setUniformSetName(String value)
  {
    setAttributeInternal(UNIFORMSETNAME, value);
  }

  /**Gets the attribute value for the calculated attribute PreparerName
   */
  public String getPreparerName()
  {
    return (String) getAttributeInternal(PREPARERNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PreparerName
   */
  public void setPreparerName(String value)
  {
    setAttributeInternal(PREPARERNAME, value);
  }

  /**Gets the attribute value for the calculated attribute RequisitionCreationDate
   */
  public Date getRequisitionCreationDate()
  {
    return (Date) getAttributeInternal(REQUISITIONCREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RequisitionCreationDate
   */
  public void setRequisitionCreationDate(Date value)
  {
    setAttributeInternal(REQUISITIONCREATIONDATE, value);
  }

  /**Gets the attribute value for the calculated attribute ContactNumber
   */
  public String getContactNumber()
  {
    return (String) getAttributeInternal(CONTACTNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ContactNumber
   */
  public void setContactNumber(String value)
  {
    setAttributeInternal(CONTACTNUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute Requisitionnumber
   */
  public String getRequisitionnumber()
  {
    return (String) getAttributeInternal(REQUISITIONNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Requisitionnumber
   */
  public void setRequisitionnumber(String value)
  {
    setAttributeInternal(REQUISITIONNUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute RequisitionType
   */
  public String getRequisitionType()
  {
    return (String) getAttributeInternal(REQUISITIONTYPE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RequisitionType
   */
  public void setRequisitionType(String value)
  {
    setAttributeInternal(REQUISITIONTYPE, value);
  }

  /**Gets the attribute value for the calculated attribute ApproverName
   */
  public String getApproverName()
  {
    return (String) getAttributeInternal(APPROVERNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverName
   */
  public void setApproverName(String value)
  {
    setAttributeInternal(APPROVERNAME, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    switch (index)
    {
      case TRANSACTIONHEADERID:
        return getTransactionHeaderId();
      case REQUISITIONHEADERID:
        return getRequisitionHeaderId();
      case TRANSACTIONTYPE:
        return getTransactionType();
      case RETURNTYPE:
        return getReturnType();
      case TRANSACTIONNUMBER:
        return getTransactionNumber();
      case TRANSACTIONSTATUS:
        return getTransactionStatus();
      case TRANSACTIONDATE:
        return getTransactionDate();
      case UNIFORMSETID:
        return getUniformSetId();
      case PERSONID:
        return getPersonId();
      case BUSINESSGROUPID:
        return getBusinessGroupId();
      case REMARKS:
        return getRemarks();
      case CREATEDBY:
        return getCreatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case ATTRIBUTE1:
        return getAttribute1();
      case ATTRIBUTE2:
        return getAttribute2();
      case ATTRIBUTE3:
        return getAttribute3();
      case ATTRIBUTE4:
        return getAttribute4();
      case ATTRIBUTE5:
        return getAttribute5();
      case ATTRIBUTE6:
        return getAttribute6();
      case ATTRIBUTE7:
        return getAttribute7();
      case ATTRIBUTE8:
        return getAttribute8();
      case ATTRIBUTE9:
        return getAttribute9();
      case ATTRIBUTE10:
        return getAttribute10();
      case ATTRIBUTE11:
        return getAttribute11();
      case ATTRIBUTE12:
        return getAttribute12();
      case ATTRIBUTE13:
        return getAttribute13();
      case ATTRIBUTE14:
        return getAttribute14();
      case ATTRIBUTE15:
        return getAttribute15();
      case ATTRIBUTE16:
        return getAttribute16();
      case ATTRIBUTE17:
        return getAttribute17();
      case ATTRIBUTE18:
        return getAttribute18();
      case ATTRIBUTE19:
        return getAttribute19();
      case ATTRIBUTE20:
        return getAttribute20();
      case EMPLOYEENUMBER:
        return getEmployeenumber();
      case EMPLOYEENAME:
        return getEmployeeName();
      case REQUISITIONSTATUS:
        return getRequisitionStatus();
      case UNIFORMSETNAME:
        return getUniformSetName();
      case PREPARERNAME:
        return getPreparerName();
      case REQUISITIONCREATIONDATE:
        return getRequisitionCreationDate();
      case CONTACTNUMBER:
        return getContactNumber();
      case REQUISITIONNUMBER:
        return getRequisitionnumber();
      case REQUISITIONTYPE:
        return getRequisitionType();
      case APPROVERNAME:
        return getApproverName();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    switch (index)
    {
      case TRANSACTIONHEADERID:
        setTransactionHeaderId((Number)value);
        return;
      case REQUISITIONHEADERID:
        setRequisitionHeaderId((Number)value);
        return;
      case TRANSACTIONTYPE:
        setTransactionType((String)value);
        return;
      case RETURNTYPE:
        setReturnType((String)value);
        return;
      case TRANSACTIONNUMBER:
        setTransactionNumber((String)value);
        return;
      case TRANSACTIONSTATUS:
        setTransactionStatus((String)value);
        return;
      case TRANSACTIONDATE:
        setTransactionDate((Date)value);
        return;
      case UNIFORMSETID:
        setUniformSetId((Number)value);
        return;
      case PERSONID:
        setPersonId((Number)value);
        return;
      case BUSINESSGROUPID:
        setBusinessGroupId((Number)value);
        return;
      case REMARKS:
        setRemarks((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case ATTRIBUTE2:
        setAttribute2((String)value);
        return;
      case ATTRIBUTE3:
        setAttribute3((String)value);
        return;
      case ATTRIBUTE4:
        setAttribute4((String)value);
        return;
      case ATTRIBUTE5:
        setAttribute5((String)value);
        return;
      case ATTRIBUTE6:
        setAttribute6((String)value);
        return;
      case ATTRIBUTE7:
        setAttribute7((String)value);
        return;
      case ATTRIBUTE8:
        setAttribute8((String)value);
        return;
      case ATTRIBUTE9:
        setAttribute9((String)value);
        return;
      case ATTRIBUTE10:
        setAttribute10((String)value);
        return;
      case ATTRIBUTE11:
        setAttribute11((String)value);
        return;
      case ATTRIBUTE12:
        setAttribute12((String)value);
        return;
      case ATTRIBUTE13:
        setAttribute13((String)value);
        return;
      case ATTRIBUTE14:
        setAttribute14((String)value);
        return;
      case ATTRIBUTE15:
        setAttribute15((String)value);
        return;
      case ATTRIBUTE16:
        setAttribute16((String)value);
        return;
      case ATTRIBUTE17:
        setAttribute17((String)value);
        return;
      case ATTRIBUTE18:
        setAttribute18((String)value);
        return;
      case ATTRIBUTE19:
        setAttribute19((String)value);
        return;
      case ATTRIBUTE20:
        setAttribute20((String)value);
        return;
      case EMPLOYEENUMBER:
        setEmployeenumber((String)value);
        return;
      case EMPLOYEENAME:
        setEmployeeName((String)value);
        return;
      case REQUISITIONSTATUS:
        setRequisitionStatus((String)value);
        return;
      case UNIFORMSETNAME:
        setUniformSetName((String)value);
        return;
      case PREPARERNAME:
        setPreparerName((String)value);
        return;
      case REQUISITIONCREATIONDATE:
        setRequisitionCreationDate((Date)value);
        return;
      case CONTACTNUMBER:
        setContactNumber((String)value);
        return;
      case REQUISITIONNUMBER:
        setRequisitionnumber((String)value);
        return;
      case REQUISITIONTYPE:
        setRequisitionType((String)value);
        return;
      case APPROVERNAME:
        setApproverName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }
}
